// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AcceptInviteData, AcceptInviteResponses, CreateIngredientData, CreateIngredientResponses, CreateRecipeData, CreateRecipeIngredientData, CreateRecipeIngredientResponses, CreateRecipeResponses, CreateRecipeStepData, CreateRecipeStepResponses, CreateUserData, CreateUserResponses, CreateWorkspaceData, CreateWorkspaceInviteData, CreateWorkspaceInviteResponses, CreateWorkspaceRecipeData, CreateWorkspaceRecipeResponses, CreateWorkspaceResponses, DeleteIngredientData, DeleteIngredientResponses, DeleteRecipeData, DeleteRecipeIngredientData, DeleteRecipeIngredientResponses, DeleteRecipeResponses, DeleteRecipeStepData, DeleteRecipeStepResponses, DeleteUserData, DeleteUserResponses, DeleteWorkspaceData, DeleteWorkspaceResponses, GetAllIngredientsData, GetAllIngredientsResponses, GetAllRecipeIngredientsData, GetAllRecipeIngredientsResponses, GetAllRecipesData, GetAllRecipesResponses, GetAllRecipeStepsData, GetAllRecipeStepsResponses, GetAllUnitsData, GetAllUnitsResponses, GetAllUsersData, GetAllUsersResponses, GetAllWorkspacesData, GetAllWorkspacesResponses, GetIngredientByIdData, GetIngredientByIdResponses, GetInviteByTokenData, GetInviteByTokenResponses, GetRecipeByIdData, GetRecipeByIdResponses, GetRecipeIngredientByIdData, GetRecipeIngredientByIdResponses, GetRecipeStepByIdData, GetRecipeStepByIdResponses, GetUserByIdData, GetUserByIdResponses, GetWorkspaceByIdData, GetWorkspaceByIdResponses, UpdateIngredientData, UpdateIngredientResponses, UpdateRecipeData, UpdateRecipeIngredientData, UpdateRecipeIngredientResponses, UpdateRecipeResponses, UpdateRecipeStepData, UpdateRecipeStepResponses, UpdateUserData, UpdateUserResponses, UpdateWorkspaceData, UpdateWorkspaceResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const deleteWorkspace = <ThrowOnError extends boolean = false>(options: Options<DeleteWorkspaceData, ThrowOnError>): RequestResult<DeleteWorkspaceResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteWorkspaceResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{id}', ...options });

export const getWorkspaceById = <ThrowOnError extends boolean = false>(options: Options<GetWorkspaceByIdData, ThrowOnError>): RequestResult<GetWorkspaceByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetWorkspaceByIdResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{id}', ...options });

export const updateWorkspace = <ThrowOnError extends boolean = false>(options: Options<UpdateWorkspaceData, ThrowOnError>): RequestResult<UpdateWorkspaceResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateWorkspaceResponses, unknown, ThrowOnError>({
    url: '/api/workspaces/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>): RequestResult<DeleteUserResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteUserResponses, unknown, ThrowOnError>({ url: '/api/users/{id}', ...options });

export const getUserById = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdData, ThrowOnError>): RequestResult<GetUserByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetUserByIdResponses, unknown, ThrowOnError>({ url: '/api/users/{id}', ...options });

export const updateUser = <ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>): RequestResult<UpdateUserResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateUserResponses, unknown, ThrowOnError>({
    url: '/api/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteRecipe = <ThrowOnError extends boolean = false>(options: Options<DeleteRecipeData, ThrowOnError>): RequestResult<DeleteRecipeResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteRecipeResponses, unknown, ThrowOnError>({ url: '/api/recipes/{id}', ...options });

export const getRecipeById = <ThrowOnError extends boolean = false>(options: Options<GetRecipeByIdData, ThrowOnError>): RequestResult<GetRecipeByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetRecipeByIdResponses, unknown, ThrowOnError>({ url: '/api/recipes/{id}', ...options });

export const updateRecipe = <ThrowOnError extends boolean = false>(options: Options<UpdateRecipeData, ThrowOnError>): RequestResult<UpdateRecipeResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateRecipeResponses, unknown, ThrowOnError>({
    url: '/api/recipes/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteRecipeStep = <ThrowOnError extends boolean = false>(options: Options<DeleteRecipeStepData, ThrowOnError>): RequestResult<DeleteRecipeStepResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteRecipeStepResponses, unknown, ThrowOnError>({ url: '/api/recipe-steps/{id}', ...options });

export const getRecipeStepById = <ThrowOnError extends boolean = false>(options: Options<GetRecipeStepByIdData, ThrowOnError>): RequestResult<GetRecipeStepByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetRecipeStepByIdResponses, unknown, ThrowOnError>({ url: '/api/recipe-steps/{id}', ...options });

export const updateRecipeStep = <ThrowOnError extends boolean = false>(options: Options<UpdateRecipeStepData, ThrowOnError>): RequestResult<UpdateRecipeStepResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateRecipeStepResponses, unknown, ThrowOnError>({
    url: '/api/recipe-steps/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteRecipeIngredient = <ThrowOnError extends boolean = false>(options: Options<DeleteRecipeIngredientData, ThrowOnError>): RequestResult<DeleteRecipeIngredientResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteRecipeIngredientResponses, unknown, ThrowOnError>({ url: '/api/recipe-ingredients/{recipeId}/{ingredientsId}', ...options });

export const getRecipeIngredientById = <ThrowOnError extends boolean = false>(options: Options<GetRecipeIngredientByIdData, ThrowOnError>): RequestResult<GetRecipeIngredientByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetRecipeIngredientByIdResponses, unknown, ThrowOnError>({ url: '/api/recipe-ingredients/{recipeId}/{ingredientsId}', ...options });

export const updateRecipeIngredient = <ThrowOnError extends boolean = false>(options: Options<UpdateRecipeIngredientData, ThrowOnError>): RequestResult<UpdateRecipeIngredientResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateRecipeIngredientResponses, unknown, ThrowOnError>({
    url: '/api/recipe-ingredients/{recipeId}/{ingredientsId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteIngredient = <ThrowOnError extends boolean = false>(options: Options<DeleteIngredientData, ThrowOnError>): RequestResult<DeleteIngredientResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteIngredientResponses, unknown, ThrowOnError>({ url: '/api/ingredients/{id}', ...options });

export const getIngredientById = <ThrowOnError extends boolean = false>(options: Options<GetIngredientByIdData, ThrowOnError>): RequestResult<GetIngredientByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetIngredientByIdResponses, unknown, ThrowOnError>({ url: '/api/ingredients/{id}', ...options });

export const updateIngredient = <ThrowOnError extends boolean = false>(options: Options<UpdateIngredientData, ThrowOnError>): RequestResult<UpdateIngredientResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateIngredientResponses, unknown, ThrowOnError>({
    url: '/api/ingredients/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAllWorkspaces = <ThrowOnError extends boolean = false>(options?: Options<GetAllWorkspacesData, ThrowOnError>): RequestResult<GetAllWorkspacesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAllWorkspacesResponses, unknown, ThrowOnError>({ url: '/api/workspaces', ...options });

export const createWorkspace = <ThrowOnError extends boolean = false>(options: Options<CreateWorkspaceData, ThrowOnError>): RequestResult<CreateWorkspaceResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateWorkspaceResponses, unknown, ThrowOnError>({
    url: '/api/workspaces',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const createWorkspaceRecipe = <ThrowOnError extends boolean = false>(options: Options<CreateWorkspaceRecipeData, ThrowOnError>): RequestResult<CreateWorkspaceRecipeResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateWorkspaceRecipeResponses, unknown, ThrowOnError>({
    url: '/api/workspaces/{id}/recipes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const createWorkspaceInvite = <ThrowOnError extends boolean = false>(options: Options<CreateWorkspaceInviteData, ThrowOnError>): RequestResult<CreateWorkspaceInviteResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateWorkspaceInviteResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{id}/invites', ...options });

export const getAllUsers = <ThrowOnError extends boolean = false>(options?: Options<GetAllUsersData, ThrowOnError>): RequestResult<GetAllUsersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAllUsersResponses, unknown, ThrowOnError>({ url: '/api/users', ...options });

export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>): RequestResult<CreateUserResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateUserResponses, unknown, ThrowOnError>({
    url: '/api/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAllRecipes = <ThrowOnError extends boolean = false>(options?: Options<GetAllRecipesData, ThrowOnError>): RequestResult<GetAllRecipesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAllRecipesResponses, unknown, ThrowOnError>({ url: '/api/recipes', ...options });

export const createRecipe = <ThrowOnError extends boolean = false>(options: Options<CreateRecipeData, ThrowOnError>): RequestResult<CreateRecipeResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateRecipeResponses, unknown, ThrowOnError>({
    url: '/api/recipes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAllRecipeSteps = <ThrowOnError extends boolean = false>(options?: Options<GetAllRecipeStepsData, ThrowOnError>): RequestResult<GetAllRecipeStepsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAllRecipeStepsResponses, unknown, ThrowOnError>({ url: '/api/recipe-steps', ...options });

export const createRecipeStep = <ThrowOnError extends boolean = false>(options: Options<CreateRecipeStepData, ThrowOnError>): RequestResult<CreateRecipeStepResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateRecipeStepResponses, unknown, ThrowOnError>({
    url: '/api/recipe-steps',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAllRecipeIngredients = <ThrowOnError extends boolean = false>(options?: Options<GetAllRecipeIngredientsData, ThrowOnError>): RequestResult<GetAllRecipeIngredientsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAllRecipeIngredientsResponses, unknown, ThrowOnError>({ url: '/api/recipe-ingredients', ...options });

export const createRecipeIngredient = <ThrowOnError extends boolean = false>(options: Options<CreateRecipeIngredientData, ThrowOnError>): RequestResult<CreateRecipeIngredientResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateRecipeIngredientResponses, unknown, ThrowOnError>({
    url: '/api/recipe-ingredients',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const acceptInvite = <ThrowOnError extends boolean = false>(options: Options<AcceptInviteData, ThrowOnError>): RequestResult<AcceptInviteResponses, unknown, ThrowOnError> => (options.client ?? client).post<AcceptInviteResponses, unknown, ThrowOnError>({
    url: '/api/invites/{token}/accept',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAllIngredients = <ThrowOnError extends boolean = false>(options?: Options<GetAllIngredientsData, ThrowOnError>): RequestResult<GetAllIngredientsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAllIngredientsResponses, unknown, ThrowOnError>({ url: '/api/ingredients', ...options });

export const createIngredient = <ThrowOnError extends boolean = false>(options: Options<CreateIngredientData, ThrowOnError>): RequestResult<CreateIngredientResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateIngredientResponses, unknown, ThrowOnError>({
    url: '/api/ingredients',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAllUnits = <ThrowOnError extends boolean = false>(options?: Options<GetAllUnitsData, ThrowOnError>): RequestResult<GetAllUnitsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAllUnitsResponses, unknown, ThrowOnError>({ url: '/api/units', ...options });

export const getInviteByToken = <ThrowOnError extends boolean = false>(options: Options<GetInviteByTokenData, ThrowOnError>): RequestResult<GetInviteByTokenResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetInviteByTokenResponses, unknown, ThrowOnError>({ url: '/api/invites/{token}', ...options });
