// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8081' | (string & {});
};

export type Ingredient = {
  id?: number;
  name?: string;
};

export type Recipe = {
  id?: number;
  name?: string;
  description?: string;
  ingredients?: Array<RecipeIngredientMapping>;
  steps?: Array<RecipeStep>;
  createdBy?: User;
  estimatedTime?: number;
  updatedAt?: string;
  createdAt?: string;
};

export type RecipeIngredientMapping = {
  id?: RecipeIngredientMappingId;
  ingredient?: Ingredient;
  amount?: number;
  unit?: string;
};

export type RecipeIngredientMappingId = {
  ingredientsId?: number;
  recipeId?: number;
};

export type RecipeStep = {
  id?: number;
  instruction?: string;
  durationMinutes?: number;
  stepNumber?: number;
};

export type User = {
  id?: number;
  firstname?: string;
  lastname?: string;
  email?: string;
  updatedAt?: string;
  createdAt?: string;
};

export type Workspace = {
  id?: number;
  name?: string;
  users?: Array<User>;
  recipes?: Array<Recipe>;
  createdAt?: string;
};

export type RecipeWritable = {
  id?: number;
  name?: string;
  description?: string;
  ingredients?: Array<RecipeIngredientMappingWritable>;
  steps?: Array<RecipeStepWritable>;
  createdBy?: UserWritable;
  estimatedTime?: number;
  updatedAt?: string;
  createdAt?: string;
};

export type RecipeIngredientMappingWritable = {
  id?: RecipeIngredientMappingId;
  recipe?: RecipeWritable;
  ingredient?: Ingredient;
  amount?: number;
  unit?: string;
};

export type RecipeStepWritable = {
  id?: number;
  recipe?: RecipeWritable;
  instruction?: string;
  durationMinutes?: number;
  stepNumber?: number;
};

export type UserWritable = {
  id?: number;
  firstname?: string;
  lastname?: string;
  email?: string;
  password?: string;
  updatedAt?: string;
  createdAt?: string;
};

export type WorkspaceWritable = {
  id?: number;
  name?: string;
  users?: Array<UserWritable>;
  recipes?: Array<RecipeWritable>;
  createdAt?: string;
};

export type DeleteWorkspaceData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/workspaces/{id}';
};

export type DeleteWorkspaceResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteWorkspaceResponse =
  DeleteWorkspaceResponses[keyof DeleteWorkspaceResponses];

export type GetWorkspaceByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/workspaces/{id}';
};

export type GetWorkspaceByIdResponses = {
  /**
   * OK
   */
  200: Workspace;
};

export type GetWorkspaceByIdResponse =
  GetWorkspaceByIdResponses[keyof GetWorkspaceByIdResponses];

export type UpdateWorkspaceData = {
  body: WorkspaceWritable;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/workspaces/{id}';
};

export type UpdateWorkspaceResponses = {
  /**
   * OK
   */
  200: Workspace;
};

export type UpdateWorkspaceResponse =
  UpdateWorkspaceResponses[keyof UpdateWorkspaceResponses];

export type DeleteUserData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type DeleteUserResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type GetUserByIdResponses = {
  /**
   * OK
   */
  200: User;
};

export type GetUserByIdResponse =
  GetUserByIdResponses[keyof GetUserByIdResponses];

export type UpdateUserData = {
  body: UserWritable;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/users/{id}';
};

export type UpdateUserResponses = {
  /**
   * OK
   */
  200: User;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type DeleteRecipeData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/recipes/{id}';
};

export type DeleteRecipeResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteRecipeResponse =
  DeleteRecipeResponses[keyof DeleteRecipeResponses];

export type GetRecipeByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/recipes/{id}';
};

export type GetRecipeByIdResponses = {
  /**
   * OK
   */
  200: Recipe;
};

export type GetRecipeByIdResponse =
  GetRecipeByIdResponses[keyof GetRecipeByIdResponses];

export type UpdateRecipeData = {
  body: RecipeWritable;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/recipes/{id}';
};

export type UpdateRecipeResponses = {
  /**
   * OK
   */
  200: Recipe;
};

export type UpdateRecipeResponse =
  UpdateRecipeResponses[keyof UpdateRecipeResponses];

export type DeleteRecipeStepData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/recipe-steps/{id}';
};

export type DeleteRecipeStepResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteRecipeStepResponse =
  DeleteRecipeStepResponses[keyof DeleteRecipeStepResponses];

export type GetRecipeStepByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/recipe-steps/{id}';
};

export type GetRecipeStepByIdResponses = {
  /**
   * OK
   */
  200: RecipeStep;
};

export type GetRecipeStepByIdResponse =
  GetRecipeStepByIdResponses[keyof GetRecipeStepByIdResponses];

export type UpdateRecipeStepData = {
  body: RecipeStepWritable;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/recipe-steps/{id}';
};

export type UpdateRecipeStepResponses = {
  /**
   * OK
   */
  200: RecipeStep;
};

export type UpdateRecipeStepResponse =
  UpdateRecipeStepResponses[keyof UpdateRecipeStepResponses];

export type DeleteRecipeIngredientData = {
  body?: never;
  path: {
    recipeId: number;
    ingredientsId: number;
  };
  query?: never;
  url: '/api/recipe-ingredients/{recipeId}/{ingredientsId}';
};

export type DeleteRecipeIngredientResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteRecipeIngredientResponse =
  DeleteRecipeIngredientResponses[keyof DeleteRecipeIngredientResponses];

export type GetRecipeIngredientByIdData = {
  body?: never;
  path: {
    recipeId: number;
    ingredientsId: number;
  };
  query?: never;
  url: '/api/recipe-ingredients/{recipeId}/{ingredientsId}';
};

export type GetRecipeIngredientByIdResponses = {
  /**
   * OK
   */
  200: RecipeIngredientMapping;
};

export type GetRecipeIngredientByIdResponse =
  GetRecipeIngredientByIdResponses[keyof GetRecipeIngredientByIdResponses];

export type UpdateRecipeIngredientData = {
  body: RecipeIngredientMappingWritable;
  path: {
    recipeId: number;
    ingredientsId: number;
  };
  query?: never;
  url: '/api/recipe-ingredients/{recipeId}/{ingredientsId}';
};

export type UpdateRecipeIngredientResponses = {
  /**
   * OK
   */
  200: RecipeIngredientMapping;
};

export type UpdateRecipeIngredientResponse =
  UpdateRecipeIngredientResponses[keyof UpdateRecipeIngredientResponses];

export type DeleteIngredientData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/ingredients/{id}';
};

export type DeleteIngredientResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteIngredientResponse =
  DeleteIngredientResponses[keyof DeleteIngredientResponses];

export type GetIngredientByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/ingredients/{id}';
};

export type GetIngredientByIdResponses = {
  /**
   * OK
   */
  200: Ingredient;
};

export type GetIngredientByIdResponse =
  GetIngredientByIdResponses[keyof GetIngredientByIdResponses];

export type UpdateIngredientData = {
  body: Ingredient;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/ingredients/{id}';
};

export type UpdateIngredientResponses = {
  /**
   * OK
   */
  200: Ingredient;
};

export type UpdateIngredientResponse =
  UpdateIngredientResponses[keyof UpdateIngredientResponses];

export type GetAllWorkspacesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/workspaces';
};

export type GetAllWorkspacesResponses = {
  /**
   * OK
   */
  200: Array<Workspace>;
};

export type GetAllWorkspacesResponse =
  GetAllWorkspacesResponses[keyof GetAllWorkspacesResponses];

export type CreateWorkspaceData = {
  body: WorkspaceWritable;
  path?: never;
  query?: never;
  url: '/api/workspaces';
};

export type CreateWorkspaceResponses = {
  /**
   * Created
   */
  201: Workspace;
};

export type CreateWorkspaceResponse =
  CreateWorkspaceResponses[keyof CreateWorkspaceResponses];

export type GetAllUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/users';
};

export type GetAllUsersResponses = {
  /**
   * OK
   */
  200: Array<User>;
};

export type GetAllUsersResponse =
  GetAllUsersResponses[keyof GetAllUsersResponses];

export type CreateUserData = {
  body: UserWritable;
  path?: never;
  query?: never;
  url: '/api/users';
};

export type CreateUserResponses = {
  /**
   * Created
   */
  201: User;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type GetAllRecipesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/recipes';
};

export type GetAllRecipesResponses = {
  /**
   * OK
   */
  200: Array<Recipe>;
};

export type GetAllRecipesResponse =
  GetAllRecipesResponses[keyof GetAllRecipesResponses];

export type CreateRecipeData = {
  body: RecipeWritable;
  path?: never;
  query?: never;
  url: '/api/recipes';
};

export type CreateRecipeResponses = {
  /**
   * Created
   */
  201: Recipe;
};

export type CreateRecipeResponse =
  CreateRecipeResponses[keyof CreateRecipeResponses];

export type GetAllRecipeStepsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/recipe-steps';
};

export type GetAllRecipeStepsResponses = {
  /**
   * OK
   */
  200: Array<RecipeStep>;
};

export type GetAllRecipeStepsResponse =
  GetAllRecipeStepsResponses[keyof GetAllRecipeStepsResponses];

export type CreateRecipeStepData = {
  body: RecipeStepWritable;
  path?: never;
  query?: never;
  url: '/api/recipe-steps';
};

export type CreateRecipeStepResponses = {
  /**
   * Created
   */
  201: RecipeStep;
};

export type CreateRecipeStepResponse =
  CreateRecipeStepResponses[keyof CreateRecipeStepResponses];

export type GetAllRecipeIngredientsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/recipe-ingredients';
};

export type GetAllRecipeIngredientsResponses = {
  /**
   * OK
   */
  200: Array<RecipeIngredientMapping>;
};

export type GetAllRecipeIngredientsResponse =
  GetAllRecipeIngredientsResponses[keyof GetAllRecipeIngredientsResponses];

export type CreateRecipeIngredientData = {
  body: RecipeIngredientMappingWritable;
  path?: never;
  query?: never;
  url: '/api/recipe-ingredients';
};

export type CreateRecipeIngredientResponses = {
  /**
   * Created
   */
  201: RecipeIngredientMapping;
};

export type CreateRecipeIngredientResponse =
  CreateRecipeIngredientResponses[keyof CreateRecipeIngredientResponses];

export type GetAllIngredientsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/ingredients';
};

export type GetAllIngredientsResponses = {
  /**
   * OK
   */
  200: Array<Ingredient>;
};

export type GetAllIngredientsResponse =
  GetAllIngredientsResponses[keyof GetAllIngredientsResponses];

export type CreateIngredientData = {
  body: Ingredient;
  path?: never;
  query?: never;
  url: '/api/ingredients';
};

export type CreateIngredientResponses = {
  /**
   * Created
   */
  201: Ingredient;
};

export type CreateIngredientResponse =
  CreateIngredientResponses[keyof CreateIngredientResponses];
